# Generated by Django 2.2.2 on 2019-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.CharField(max_length=2)),
                ('education', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('major', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
