# Generated by Django 2.2.2 on 2019-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190614_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='emial',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
