# Generated by Django 2.2.2 on 2019-06-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_contact_emial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='emial',
        ),
    ]
