# Generated by Django 2.2.2 on 2019-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_contact_emial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
